[package]
name = "life"
version = "0.1.0"
authors = ["Ian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.18.0"
clap = "*"
